[tool.poetry]
name = "ss2022b-tmurphy"
version = "0.1.0"
description = ""
authors = ["  < >"]

[tool.poetry.dependencies]
python = "^3.8"
numpy = "^1.20.0,<1.23.2"
scipy = "^1.5.2"
pyregion ="<2.1.1"
astropy = "^5.1"
aplpy = "^2.1.0"
matplotlib = "^3.5.2"
scikit-image = "^0.19.3"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
