#!/bin/bash 

sbatch vastfast_beam00.sh
sbatch vastfast_beam01.sh
sbatch vastfast_beam02.sh
sbatch vastfast_beam03.sh
sbatch vastfast_beam04.sh
sbatch vastfast_beam05.sh
sbatch vastfast_beam06.sh
sbatch vastfast_beam07.sh
sbatch vastfast_beam08.sh
sbatch vastfast_beam09.sh
sbatch vastfast_beam10.sh
sbatch vastfast_beam11.sh
sbatch vastfast_beam12.sh
sbatch vastfast_beam13.sh
sbatch vastfast_beam14.sh
sbatch vastfast_beam15.sh
sbatch vastfast_beam16.sh
sbatch vastfast_beam17.sh
sbatch vastfast_beam18.sh
sbatch vastfast_beam19.sh
sbatch vastfast_beam20.sh
sbatch vastfast_beam21.sh
sbatch vastfast_beam22.sh
sbatch vastfast_beam23.sh
sbatch vastfast_beam24.sh
sbatch vastfast_beam25.sh
sbatch vastfast_beam26.sh
sbatch vastfast_beam27.sh
sbatch vastfast_beam28.sh
sbatch vastfast_beam29.sh
sbatch vastfast_beam30.sh
sbatch vastfast_beam31.sh
sbatch vastfast_beam32.sh
sbatch vastfast_beam33.sh
sbatch vastfast_beam34.sh
sbatch vastfast_beam35.sh
